import type { Exercise } from "@/types/types";

export const exercises: Exercise[] = [
    {
        id: "adductors-1",
        name: "Cable Hip Adduction",
        primaryMuscle: "adductors",
        secondaryMuscles: [],
    },
    {
        id: "adductors-2",
        name: "Side-Lying Hip Adduction",
        primaryMuscle: "adductors",
        secondaryMuscles: [],
    },
    {
        id: "adductors-3",
        name: "Standing Adduction (band)",
        primaryMuscle: "adductors",
        secondaryMuscles: [],
    },
    {
        id: "adductors-4",
        name: "Seated Adductor Machine",
        primaryMuscle: "adductors",
        secondaryMuscles: [],
    },
    {
        id: "adductors-5",
        name: "Sumo Squat",
        primaryMuscle: "adductors",
        secondaryMuscles: ["glutes", "quads"],
    },
    {
        id: "adductors-6",
        name: "Cossack Squat",
        primaryMuscle: "adductors",
        secondaryMuscles: ["glutes", "quads"],
    },
    {
        id: "adductors-7",
        name: "Lateral Lunge",
        primaryMuscle: "adductors",
        secondaryMuscles: ["glutes", "quads"],
    },
    {
        id: "adductors-8",
        name: "Frog Pumps",
        primaryMuscle: "adductors",
        secondaryMuscles: ["glutes"],
    },
    {
        id: "adductors-9",
        name: "Dumbbell Sumo Deadlift",
        primaryMuscle: "adductors",
        secondaryMuscles: ["glutes", "hamstrings"],
    },
    {
        id: "adductors-10",
        name: "Resistance Band Adduction",
        primaryMuscle: "adductors",
        secondaryMuscles: [],
    },
    {
        id: "biceps-1",
        name: "Barbell Curl",
        primaryMuscle: "biceps",
        secondaryMuscles: ["forearms"],
    },
    {
        id: "biceps-2",
        name: "Dumbbell Curl",
        primaryMuscle: "biceps",
        secondaryMuscles: ["forearms"],
    },
    {
        id: "biceps-3",
        name: "Hammer Curl",
        primaryMuscle: "biceps",
        secondaryMuscles: ["forearms"],
    },
    {
        id: "biceps-4",
        name: "Preacher Curl",
        primaryMuscle: "biceps",
        secondaryMuscles: [],
    },
    {
        id: "biceps-5",
        name: "Concentration Curl",
        primaryMuscle: "biceps",
        secondaryMuscles: [],
    },
    {
        id: "biceps-6",
        name: "Cable Curl",
        primaryMuscle: "biceps",
        secondaryMuscles: [],
    },
    {
        id: "biceps-7",
        name: "Incline Dumbbell Curl",
        primaryMuscle: "biceps",
        secondaryMuscles: [],
    },
    {
        id: "biceps-8",
        name: "Spider Curl",
        primaryMuscle: "biceps",
        secondaryMuscles: [],
    },
    {
        id: "biceps-9",
        name: "EZ Bar Curl",
        primaryMuscle: "biceps",
        secondaryMuscles: ["forearms"],
    },
    {
        id: "biceps-10",
        name: "Reverse Curl",
        primaryMuscle: "biceps",
        secondaryMuscles: ["forearms"],
    },
    {
        id: "neck-1",
        name: "Neck Flexion",
        primaryMuscle: "neck",
        secondaryMuscles: [],
    },
    {
        id: "neck-2",
        name: "Neck Extension",
        primaryMuscle: "neck",
        secondaryMuscles: [],
    },
    {
        id: "neck-3",
        name: "Lateral Neck Flexion",
        primaryMuscle: "neck",
        secondaryMuscles: [],
    },
    {
        id: "neck-4",
        name: "Neck Bridges",
        primaryMuscle: "neck",
        secondaryMuscles: [],
    },
    {
        id: "neck-5",
        name: "Resistance Band Neck Extension",
        primaryMuscle: "neck",
        secondaryMuscles: [],
    },
    {
        id: "neck-6",
        name: "Resistance Band Neck Flexion",
        primaryMuscle: "neck",
        secondaryMuscles: [],
    },
    {
        id: "neck-7",
        name: "Harness Neck Raise",
        primaryMuscle: "neck",
        secondaryMuscles: [],
    },
    {
        id: "neck-8",
        name: "Lying Neck Isometrics",
        primaryMuscle: "neck",
        secondaryMuscles: [],
    },
    {
        id: "neck-9",
        name: "Manual Neck Resistance",
        primaryMuscle: "neck",
        secondaryMuscles: [],
    },
    {
        id: "neck-10",
        name: "Partner Assisted Neck Training",
        primaryMuscle: "neck",
        secondaryMuscles: [],
    },
    {
        id: "traps-1",
        name: "Barbell Shrug",
        primaryMuscle: "traps",
        secondaryMuscles: [],
    },
    {
        id: "traps-2",
        name: "Dumbbell Shrug",
        primaryMuscle: "traps",
        secondaryMuscles: [],
    },
    {
        id: "traps-3",
        name: "Smith Machine Shrug",
        primaryMuscle: "traps",
        secondaryMuscles: [],
    },
    {
        id: "traps-4",
        name: "Upright Row",
        primaryMuscle: "traps",
        secondaryMuscles: ["sideDelts"],
    },
    {
        id: "traps-5",
        name: "Face Pull",
        primaryMuscle: "traps",
        secondaryMuscles: ["rearDelts"],
    },
    {
        id: "traps-6",
        name: "Farmer's Walk",
        primaryMuscle: "traps",
        secondaryMuscles: ["forearms"],
    },
    {
        id: "traps-7",
        name: "Trap Bar Deadlift",
        primaryMuscle: "traps",
        secondaryMuscles: ["glutes", "hamstrings"],
    },
    {
        id: "traps-8",
        name: "Barbell High Pull",
        primaryMuscle: "traps",
        secondaryMuscles: ["rearDelts"],
    },
    {
        id: "traps-9",
        name: "Cable Shrug",
        primaryMuscle: "traps",
        secondaryMuscles: [],
    },
    {
        id: "traps-10",
        name: "Behind-the-Back Barbell Shrug",
        primaryMuscle: "traps",
        secondaryMuscles: [],
    },
    {
        id: "sideDelts-1",
        name: "Dumbbell Lateral Raise",
        primaryMuscle: "sideDelts",
        secondaryMuscles: [],
    },
    {
        id: "sideDelts-2",
        name: "Cable Lateral Raise",
        primaryMuscle: "sideDelts",
        secondaryMuscles: [],
    },
    {
        id: "sideDelts-3",
        name: "Machine Lateral Raise",
        primaryMuscle: "sideDelts",
        secondaryMuscles: [],
    },
    {
        id: "sideDelts-4",
        name: "Seated Dumbbell Lateral Raise",
        primaryMuscle: "sideDelts",
        secondaryMuscles: [],
    },
    {
        id: "sideDelts-5",
        name: "Leaning Cable Lateral Raise",
        primaryMuscle: "sideDelts",
        secondaryMuscles: [],
    },
    {
        id: "sideDelts-6",
        name: "Barbell Upright Row (Wide Grip)",
        primaryMuscle: "sideDelts",
        secondaryMuscles: [],
    },
    {
        id: "sideDelts-7",
        name: "Resistance Band Lateral Raise",
        primaryMuscle: "sideDelts",
        secondaryMuscles: [],
    },
    {
        id: "sideDelts-8",
        name: "Lying Side Dumbbell Raise",
        primaryMuscle: "sideDelts",
        secondaryMuscles: [],
    },
    {
        id: "sideDelts-9",
        name: "Cable Y Raise",
        primaryMuscle: "sideDelts",
        secondaryMuscles: [],
    },
    {
        id: "sideDelts-10",
        name: "Single-Arm Dumbbell Lateral Raise",
        primaryMuscle: "sideDelts",
        secondaryMuscles: [],
    },
    {
        id: "frontDelts-1",
        name: "Barbell Overhead Press",
        primaryMuscle: "frontDelts",
        secondaryMuscles: ["triceps", "upperChest"],
    },
    {
        id: "frontDelts-2",
        name: "Dumbbell Front Raise",
        primaryMuscle: "frontDelts",
        secondaryMuscles: [],
    },
    {
        id: "frontDelts-3",
        name: "Cable Front Raise",
        primaryMuscle: "frontDelts",
        secondaryMuscles: [],
    },
    {
        id: "frontDelts-4",
        name: "Arnold Press",
        primaryMuscle: "frontDelts",
        secondaryMuscles: ["sideDelts", "triceps"],
    },
    {
        id: "frontDelts-5",
        name: "Machine Shoulder Press",
        primaryMuscle: "frontDelts",
        secondaryMuscles: ["triceps"],
    },
    {
        id: "frontDelts-6",
        name: "Landmine Press",
        primaryMuscle: "frontDelts",
        secondaryMuscles: ["triceps", "chest"],
    },
    {
        id: "frontDelts-7",
        name: "Resistance Band Front Raise",
        primaryMuscle: "frontDelts",
        secondaryMuscles: [],
    },
    {
        id: "frontDelts-8",
        name: "Incline Front Raise",
        primaryMuscle: "frontDelts",
        secondaryMuscles: [],
    },
    {
        id: "frontDelts-9",
        name: "Plate Front Raise",
        primaryMuscle: "frontDelts",
        secondaryMuscles: [],
    },
    {
        id: "frontDelts-10",
        name: "Z Press",
        primaryMuscle: "frontDelts",
        secondaryMuscles: ["triceps", "core"],
    },
    {
        id: "forearms-1",
        name: "Wrist Curl",
        primaryMuscle: "forearms",
        secondaryMuscles: [],
    },
    {
        id: "forearms-2",
        name: "Reverse Wrist Curl",
        primaryMuscle: "forearms",
        secondaryMuscles: [],
    },
    {
        id: "forearms-3",
        name: "Hammer Curl",
        primaryMuscle: "forearms",
        secondaryMuscles: ["biceps"],
    },
    {
        id: "forearms-4",
        name: "Farmer's Carry",
        primaryMuscle: "forearms",
        secondaryMuscles: ["traps"],
    },
    {
        id: "forearms-5",
        name: "Dead Hang",
        primaryMuscle: "forearms",
        secondaryMuscles: ["lats"],
    },
    {
        id: "forearms-6",
        name: "Towel Pull-Ups",
        primaryMuscle: "forearms",
        secondaryMuscles: ["lats", "biceps"],
    },
    {
        id: "forearms-7",
        name: "Wrist Roller",
        primaryMuscle: "forearms",
        secondaryMuscles: [],
    },
    {
        id: "forearms-8",
        name: "Finger Curls",
        primaryMuscle: "forearms",
        secondaryMuscles: [],
    },
    {
        id: "forearms-9",
        name: "Plate Pinch Hold",
        primaryMuscle: "forearms",
        secondaryMuscles: [],
    },
    {
        id: "forearms-10",
        name: "Rope Climbs",
        primaryMuscle: "forearms",
        secondaryMuscles: ["biceps", "lats"],
    },
    {
        id: "chest-1",
        name: "Barbell Bench Press",
        primaryMuscle: "chest",
        secondaryMuscles: ["triceps", "frontDelts"],
    },
    {
        id: "chest-2",
        name: "Dumbbell Bench Press",
        primaryMuscle: "chest",
        secondaryMuscles: ["triceps", "frontDelts"],
    },
    {
        id: "chest-3",
        name: "Incline Barbell Press",
        primaryMuscle: "chest",
        secondaryMuscles: ["triceps", "frontDelts"],
    },
    {
        id: "chest-4",
        name: "Incline Dumbbell Press",
        primaryMuscle: "chest",
        secondaryMuscles: ["triceps", "frontDelts"],
    },
    {
        id: "chest-5",
        name: "Chest Fly (Machine or Dumbbell)",
        primaryMuscle: "chest",
        secondaryMuscles: [],
    },
    {
        id: "chest-6",
        name: "Cable Crossover",
        primaryMuscle: "chest",
        secondaryMuscles: [],
    },
    {
        id: "chest-7",
        name: "Push-Up",
        primaryMuscle: "chest",
        secondaryMuscles: ["triceps", "frontDelts"],
    },
    {
        id: "chest-8",
        name: "Dips (Chest Focus)",
        primaryMuscle: "chest",
        secondaryMuscles: ["triceps", "frontDelts"],
    },
    {
        id: "chest-9",
        name: "Pec Deck Machine",
        primaryMuscle: "chest",
        secondaryMuscles: [],
    },
    {
        id: "chest-10",
        name: "Single-Arm Cable Fly",
        primaryMuscle: "chest",
        secondaryMuscles: [],
    },
    {
        id: "chest-11",
        name: "Incline Machine Press",
        primaryMuscle: "chest",
        secondaryMuscles: ["triceps", "frontDelts"],
    },
    {
        id: "lats-1",
        name: "Pull-Up",
        primaryMuscle: "lats",
        secondaryMuscles: ["biceps"],
    },
    {
        id: "lats-2",
        name: "Chin-Up",
        primaryMuscle: "lats",
        secondaryMuscles: ["biceps"],
    },
    {
        id: "lats-3",
        name: "Lat Pulldown",
        primaryMuscle: "lats",
        secondaryMuscles: ["biceps"],
    },
    {
        id: "lats-4",
        name: "Straight Arm Pulldown",
        primaryMuscle: "lats",
        secondaryMuscles: [],
    },
    {
        id: "lats-5",
        name: "Barbell Row",
        primaryMuscle: "lats",
        secondaryMuscles: ["rearDelts", "rhomboids"],
    },
    {
        id: "lats-6",
        name: "Single-Arm Dumbbell Row",
        primaryMuscle: "lats",
        secondaryMuscles: ["rearDelts", "rhomboids"],
    },
    {
        id: "lats-7",
        name: "Seal Row",
        primaryMuscle: "lats",
        secondaryMuscles: ["rearDelts", "rhomboids"],
    },
    {
        id: "lats-8",
        name: "Inverted Row",
        primaryMuscle: "lats",
        secondaryMuscles: ["biceps", "rearDelts"],
    },
    {
        id: "lats-9",
        name: "T-Bar Row",
        primaryMuscle: "lats",
        secondaryMuscles: ["rearDelts", "rhomboids"],
    },
    {
        id: "lats-10",
        name: "Cable Row",
        primaryMuscle: "lats",
        secondaryMuscles: ["rearDelts", "rhomboids"],
    },
    {
        id: "abs-1",
        name: "Crunches",
        primaryMuscle: "abs",
        secondaryMuscles: [],
    },
    {
        id: "abs-2",
        name: "Hanging Leg Raise",
        primaryMuscle: "abs",
        secondaryMuscles: ["hipFlexors"],
    },
    {
        id: "abs-3",
        name: "Cable Crunch",
        primaryMuscle: "abs",
        secondaryMuscles: [],
    },
    {
        id: "abs-4",
        name: "Weighted Sit-Up",
        primaryMuscle: "abs",
        secondaryMuscles: [],
    },
    {
        id: "abs-5",
        name: "Plank",
        primaryMuscle: "abs",
        secondaryMuscles: ["core"],
    },
    {
        id: "abs-6",
        name: "V-Ups",
        primaryMuscle: "abs",
        secondaryMuscles: ["hipFlexors"],
    },
    {
        id: "abs-7",
        name: "Decline Crunch",
        primaryMuscle: "abs",
        secondaryMuscles: [],
    },
    {
        id: "abs-8",
        name: "Toe Touches",
        primaryMuscle: "abs",
        secondaryMuscles: [],
    },
    {
        id: "abs-9",
        name: "Dead Bug",
        primaryMuscle: "abs",
        secondaryMuscles: ["core"],
    },
    {
        id: "abs-10",
        name: "Weighted Plank",
        primaryMuscle: "abs",
        secondaryMuscles: ["core"],
    },
    {
        id: "obliques-1",
        name: "Russian Twist",
        primaryMuscle: "obliques",
        secondaryMuscles: ["abs"],
    },
    {
        id: "obliques-2",
        name: "Side Plank",
        primaryMuscle: "obliques",
        secondaryMuscles: ["abs", "core"],
    },
    {
        id: "obliques-3",
        name: "Cable Woodchopper",
        primaryMuscle: "obliques",
        secondaryMuscles: ["abs"],
    },
    {
        id: "obliques-4",
        name: "Oblique Crunch",
        primaryMuscle: "obliques",
        secondaryMuscles: ["abs"],
    },
    {
        id: "obliques-5",
        name: "Hanging Oblique Knee Raise",
        primaryMuscle: "obliques",
        secondaryMuscles: ["abs", "hipFlexors"],
    },
    {
        id: "obliques-6",
        name: "Standing Oblique Crunch",
        primaryMuscle: "obliques",
        secondaryMuscles: ["abs"],
    },
    {
        id: "obliques-7",
        name: "Dumbbell Side Bend",
        primaryMuscle: "obliques",
        secondaryMuscles: [],
    },
    {
        id: "obliques-8",
        name: "Landmine Twist",
        primaryMuscle: "obliques",
        secondaryMuscles: ["abs"],
    },
    {
        id: "obliques-9",
        name: "Bicycle Crunch",
        primaryMuscle: "obliques",
        secondaryMuscles: ["abs"],
    },
    {
        id: "obliques-10",
        name: "Plank with Hip Dips",
        primaryMuscle: "obliques",
        secondaryMuscles: ["abs", "core"],
    },
    {
        id: "quads-1",
        name: "Barbell Back Squat",
        primaryMuscle: "quads",
        secondaryMuscles: ["glutes", "hamstrings"],
    },
    {
        id: "quads-2",
        name: "Front Squat",
        primaryMuscle: "quads",
        secondaryMuscles: ["glutes", "core"],
    },
    {
        id: "quads-3",
        name: "Bulgarian Split Squat",
        primaryMuscle: "quads",
        secondaryMuscles: ["glutes", "hamstrings"],
    },
    {
        id: "quads-4",
        name: "Leg Press",
        primaryMuscle: "quads",
        secondaryMuscles: ["glutes"],
    },
    {
        id: "quads-5",
        name: "Walking Lunge",
        primaryMuscle: "quads",
        secondaryMuscles: ["glutes", "hamstrings"],
    },
    {
        id: "quads-6",
        name: "Step-Up",
        primaryMuscle: "quads",
        secondaryMuscles: ["glutes"],
    },
    {
        id: "quads-7",
        name: "Hack Squat (Machine)",
        primaryMuscle: "quads",
        secondaryMuscles: ["glutes"],
    },
    {
        id: "quads-8",
        name: "Sissy Squat",
        primaryMuscle: "quads",
        secondaryMuscles: [],
    },
    {
        id: "quads-9",
        name: "Smith Machine Squat",
        primaryMuscle: "quads",
        secondaryMuscles: ["glutes"],
    },
    {
        id: "quads-10",
        name: "Goblet Squat",
        primaryMuscle: "quads",
        secondaryMuscles: ["glutes"],
    },
    {
        id: "quads-11",
        name: "Leg Extension",
        primaryMuscle: "quads",
        secondaryMuscles: [],
    },
    {
        id: "calves-1",
        name: "Standing Calf Raise",
        primaryMuscle: "calves",
        secondaryMuscles: [],
    },
    {
        id: "calves-2",
        name: "Seated Calf Raise",
        primaryMuscle: "calves",
        secondaryMuscles: [],
    },
    {
        id: "calves-3",
        name: "Donkey Calf Raise",
        primaryMuscle: "calves",
        secondaryMuscles: [],
    },
    {
        id: "calves-4",
        name: "Single-Leg Calf Raise",
        primaryMuscle: "calves",
        secondaryMuscles: [],
    },
    {
        id: "calves-5",
        name: "Smith Machine Calf Raise",
        primaryMuscle: "calves",
        secondaryMuscles: [],
    },
    {
        id: "calves-6",
        name: "Leg Press Calf Raise",
        primaryMuscle: "calves",
        secondaryMuscles: [],
    },
    {
        id: "calves-7",
        name: "Resistance Band Calf Raise",
        primaryMuscle: "calves",
        secondaryMuscles: [],
    },
    {
        id: "calves-8",
        name: "Farmer's Walk on Toes",
        primaryMuscle: "calves",
        secondaryMuscles: [],
    },
    {
        id: "calves-9",
        name: "Jump Rope",
        primaryMuscle: "calves",
        secondaryMuscles: [],
    },
    {
        id: "calves-10",
        name: "Tibialis Raise",
        primaryMuscle: "calves",
        secondaryMuscles: [],
    },
    {
        id: "abductors-1",
        name: "Cable Hip Abduction",
        primaryMuscle: "abductors",
        secondaryMuscles: [],
    },
    {
        id: "abductors-2",
        name: "Seated Hip Abduction Machine",
        primaryMuscle: "abductors",
        secondaryMuscles: [],
    },
    {
        id: "abductors-3",
        name: "Side-Lying Hip Raise",
        primaryMuscle: "abductors",
        secondaryMuscles: [],
    },
    {
        id: "abductors-4",
        name: "Banded Lateral Walk",
        primaryMuscle: "abductors",
        secondaryMuscles: [],
    },
    {
        id: "abductors-5",
        name: "Standing Cable Hip Abduction",
        primaryMuscle: "abductors",
        secondaryMuscles: [],
    },
    {
        id: "abductors-6",
        name: "Clamshells",
        primaryMuscle: "abductors",
        secondaryMuscles: ["glutes"],
    },
    {
        id: "abductors-7",
        name: "Fire Hydrant",
        primaryMuscle: "abductors",
        secondaryMuscles: ["glutes"],
    },
    {
        id: "abductors-8",
        name: "Resistance Band Hip Abduction",
        primaryMuscle: "abductors",
        secondaryMuscles: [],
    },
    {
        id: "abductors-9",
        name: "Cable Kick-Out",
        primaryMuscle: "abductors",
        secondaryMuscles: ["glutes"],
    },
    {
        id: "abductors-10",
        name: "Side Plank with Hip Abduction",
        primaryMuscle: "abductors",
        secondaryMuscles: ["core"],
    },
    {
        id: "hamstrings-1",
        name: "Romanian Deadlift",
        primaryMuscle: "hamstrings",
        secondaryMuscles: ["glutes", "lowerBack"],
    },
    {
        id: "hamstrings-2",
        name: "Seated Leg Curl",
        primaryMuscle: "hamstrings",
        secondaryMuscles: [],
    },
    {
        id: "hamstrings-3",
        name: "Lying Leg Curl",
        primaryMuscle: "hamstrings",
        secondaryMuscles: [],
    },
    {
        id: "hamstrings-4",
        name: "Good Mornings",
        primaryMuscle: "hamstrings",
        secondaryMuscles: ["glutes", "lowerBack"],
    },
    {
        id: "hamstrings-5",
        name: "Nordic Hamstring Curl",
        primaryMuscle: "hamstrings",
        secondaryMuscles: [],
    },
    {
        id: "hamstrings-6",
        name: "Stiff-Leg Deadlift",
        primaryMuscle: "hamstrings",
        secondaryMuscles: ["glutes", "lowerBack"],
    },
    {
        id: "hamstrings-7",
        name: "Glute-Ham Raise",
        primaryMuscle: "hamstrings",
        secondaryMuscles: ["glutes"],
    },
    {
        id: "hamstrings-8",
        name: "Single-Leg Romanian Deadlift",
        primaryMuscle: "hamstrings",
        secondaryMuscles: ["glutes", "core"],
    },
    {
        id: "hamstrings-9",
        name: "Cable Pull-Through",
        primaryMuscle: "hamstrings",
        secondaryMuscles: ["glutes"],
    },
    {
        id: "hamstrings-10",
        name: "Kettlebell Swing",
        primaryMuscle: "hamstrings",
        secondaryMuscles: ["glutes", "lowerBack"],
    },
    {
        id: "rearDelts-1",
        name: "Face Pull",
        primaryMuscle: "rearDelts",
        secondaryMuscles: ["traps"],
    },
    {
        id: "rearDelts-2",
        name: "Reverse Pec Deck Fly",
        primaryMuscle: "rearDelts",
        secondaryMuscles: ["rhomboids"],
    },
    {
        id: "rearDelts-3",
        name: "Bent-Over Dumbbell Reverse Fly",
        primaryMuscle: "rearDelts",
        secondaryMuscles: ["rhomboids"],
    },
    {
        id: "rearDelts-4",
        name: "Cable Rear Delt Fly",
        primaryMuscle: "rearDelts",
        secondaryMuscles: ["rhomboids"],
    },
    {
        id: "rearDelts-5",
        name: "Rear Delt Row",
        primaryMuscle: "rearDelts",
        secondaryMuscles: ["rhomboids"],
    },
    {
        id: "rearDelts-6",
        name: "Barbell Face Pull",
        primaryMuscle: "rearDelts",
        secondaryMuscles: ["traps"],
    },
    {
        id: "rearDelts-7",
        name: "Incline Rear Delt Raise",
        primaryMuscle: "rearDelts",
        secondaryMuscles: ["rhomboids"],
    },
    {
        id: "rearDelts-8",
        name: "Resistance Band Face Pull",
        primaryMuscle: "rearDelts",
        secondaryMuscles: ["rhomboids"],
    },
    {
        id: "rearDelts-9",
        name: "Reverse Cable Crossover",
        primaryMuscle: "rearDelts",
        secondaryMuscles: ["rhomboids"],
    },
    {
        id: "rearDelts-10",
        name: "Chest-Supported Rear Delt Fly",
        primaryMuscle: "rearDelts",
        secondaryMuscles: ["rhomboids"],
    },
    {
        id: "rearDelts-11",
        name: "Rear Delt Pulldown",
        primaryMuscle: "rearDelts",
        secondaryMuscles: ["rhomboids"],
    },
    {
        id: "rhomboids-1",
        name: "Face Pull",
        primaryMuscle: "rhomboids",
        secondaryMuscles: ["rearDelts", "traps"],
    },
    {
        id: "rhomboids-2",
        name: "Seated Cable Row",
        primaryMuscle: "rhomboids",
        secondaryMuscles: ["lats", "rearDelts"],
    },
    {
        id: "rhomboids-3",
        name: "Barbell Row",
        primaryMuscle: "rhomboids",
        secondaryMuscles: ["lats", "rearDelts", "biceps"],
    },
    {
        id: "rhomboids-4",
        name: "T-Bar Row",
        primaryMuscle: "rhomboids",
        secondaryMuscles: ["lats", "traps"],
    },
    {
        id: "rhomboids-5",
        name: "Chest-Supported Row",
        primaryMuscle: "rhomboids",
        secondaryMuscles: ["lats", "rearDelts"],
    },
    {
        id: "rhomboids-6",
        name: "Dumbbell Row",
        primaryMuscle: "rhomboids",
        secondaryMuscles: ["lats", "biceps"],
    },
    {
        id: "rhomboids-7",
        name: "Inverted Row",
        primaryMuscle: "rhomboids",
        secondaryMuscles: ["lats", "biceps"],
    },
    {
        id: "rhomboids-8",
        name: "Resistance Band Row",
        primaryMuscle: "rhomboids",
        secondaryMuscles: ["rearDelts"],
    },
    {
        id: "rhomboids-9",
        name: "Pendlay Row",
        primaryMuscle: "rhomboids",
        secondaryMuscles: ["lats", "rearDelts"],
    },
    {
        id: "rhomboids-10",
        name: "Reverse Machine Fly",
        primaryMuscle: "rhomboids",
        secondaryMuscles: ["rearDelts"],
    },
    {
        id: "triceps-1",
        name: "Close-Grip Bench Press",
        primaryMuscle: "triceps",
        secondaryMuscles: ["chest", "shoulders"],
    },
    {
        id: "triceps-2",
        name: "Dips",
        primaryMuscle: "triceps",
        secondaryMuscles: ["chest", "shoulders"],
    },
    {
        id: "triceps-3",
        name: "Overhead Tricep Extension",
        primaryMuscle: "triceps",
        secondaryMuscles: [],
    },
    {
        id: "triceps-4",
        name: "Tricep Pushdown (Cable)",
        primaryMuscle: "triceps",
        secondaryMuscles: [],
    },
    {
        id: "triceps-5",
        name: "Skull Crushers",
        primaryMuscle: "triceps",
        secondaryMuscles: [],
    },
    {
        id: "triceps-6",
        name: "Kickbacks",
        primaryMuscle: "triceps",
        secondaryMuscles: [],
    },
    {
        id: "triceps-7",
        name: "Diamond Push-Up",
        primaryMuscle: "triceps",
        secondaryMuscles: ["chest", "shoulders"],
    },
    {
        id: "triceps-8",
        name: "Bench Dip",
        primaryMuscle: "triceps",
        secondaryMuscles: [],
    },
    {
        id: "triceps-9",
        name: "Single-Arm Cable Pushdown",
        primaryMuscle: "triceps",
        secondaryMuscles: [],
    },
    {
        id: "triceps-10",
        name: "Resistance Band Tricep Extension",
        primaryMuscle: "triceps",
        secondaryMuscles: [],
    },
    {
        id: "glutes-1",
        name: "Hip Thrust",
        primaryMuscle: "glutes",
        secondaryMuscles: ["hamstrings"],
    },
    {
        id: "glutes-2",
        name: "Barbell Glute Bridge",
        primaryMuscle: "glutes",
        secondaryMuscles: ["hamstrings", "core"],
    },
    {
        id: "glutes-3",
        name: "Bulgarian Split Squat",
        primaryMuscle: "glutes",
        secondaryMuscles: ["quads", "hamstrings"],
    },
    {
        id: "glutes-4",
        name: "Walking Lunge",
        primaryMuscle: "glutes",
        secondaryMuscles: ["quads", "hamstrings"],
    },
    {
        id: "glutes-5",
        name: "Cable Kickback",
        primaryMuscle: "glutes",
        secondaryMuscles: ["hamstrings"],
    },
    {
        id: "glutes-6",
        name: "Sumo Deadlift",
        primaryMuscle: "glutes",
        secondaryMuscles: ["hamstrings", "quads"],
    },
    {
        id: "glutes-7",
        name: "Step-Up",
        primaryMuscle: "glutes",
        secondaryMuscles: ["quads", "hamstrings"],
    },
    {
        id: "glutes-8",
        name: "Romanian Deadlift",
        primaryMuscle: "glutes",
        secondaryMuscles: ["hamstrings", "lowerBack"],
    },
    {
        id: "glutes-9",
        name: "Fire Hydrant",
        primaryMuscle: "glutes",
        secondaryMuscles: ["abductors"],
    },
    {
        id: "glutes-10",
        name: "Clamshells",
        primaryMuscle: "glutes",
        secondaryMuscles: ["abductors"],
    },
    {
        id: "glutes-11",
        name: "Hyperextension",
        primaryMuscle: "glutes",
        secondaryMuscles: ["hamstrings"],
    },
] as const;
